name: LibraryEnforce
version: 1.0
author: jamietech
website: http://jamiete.ch
main: ch.jamiete.library.Shhhhh

permissions:
  libraryenforce.librarian:
    description: Allows librarians to ignore the restrictions
    default: OP